wandb_version: 1

base_learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: Sparse 2-layer MPNN
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: CosineAnnealingWarmRestarts
dataset:
  desc: null
  value: QM9
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 128
name:
  desc: null
  value: 2LC
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713403049.0
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.11.8
      5: 0.16.4
      8:
      - 1
      - 5
      13: darwin-x86_64
